// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Error - unexpected error
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}
